version: '2'

services:
    memcached:
        image: memcached:alpine
        container_name: tw_memcached
    db:
        image: mysql:5.7
        container_name: tw_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build:
            context: docker/php7-fpm
        container_name: tw_php
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony:rw
            - ${SYMFONY_APP_PATH}/var/log/nginx:/var/log/nginx/:rw
    nginx:
        image: nginx:alpine
        container_name: tw_nginx
        ports:
            - "80:80"
        volumes_from:
            - php
        volumes:
            - ${SYMFONY_APP_PATH}/docker/nginx/symfony.conf:/etc/nginx/conf.d/default.conf:cached
            - ${SYMFONY_APP_PATH}/var/log/nginx:/var/log/nginx/:rw
        extra_hosts:
            - ${SYMFONY_APP_URL}:127.0.0.1
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION_TAG}
        container_name: tw_elasticsearch
        environment:
          - cluster.name=bayday-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - ${SYMFONY_APP_PATH}/.data:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
    kibana:
        image: docker.elastic.co/kibana/kibana:${ELK_VERSION_TAG}
        container_name: tw_kibana
        ports:
          - 5601:5601
    logstash:
        image: docker.elastic.co/logstash/logstash:${ELK_VERSION_TAG}
        container_name: tw_logstash
        environment:
            XPACK_MONITORING_ENABLED: "true"
        ports:
            - 5044:5044
            - 9600:9600
        volumes:
            - ${SYMFONY_APP_PATH}/docker/logstash/patterns:/usr/share/logstash/patterns:cached
            - ${SYMFONY_APP_PATH}/docker/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:cached
            - ${SYMFONY_APP_PATH}/var/log/logstash:/usr/share/logstash/logs:rw
        volumes_from:
            - php
            - nginx
